import = ["~/.config/alacritty/gruvbox_dark.toml"]

[colors]
draw_bold_text_with_bright_colors = true

[font]
size = 13

[[keyboard.bindings]]
action = "ScrollLineUp"
key = "Up"
mods = "Shift"

[[keyboard.bindings]]
action = "ScrollLineDown"
key = "Down"
mods = "Shift"

[[keyboard.bindings]]
action = "ResetFontSize"
key = 11
mods = "Control"
