add_newline = false

format = """
$hostname\
$directory\
$git_branch\
$git_commit\
$git_state\
$git_status\
$cmd_duration\
$jobs\
$status\
$character"""

[hostname]
ssh_symbol = ""

[cmd_duration]
min_time = 5_000
