"====================
" Plugins (vim-plug)
"====================

call plug#begin()

Plug 'ctrlpvim/ctrlp.vim'
Plug 'scrooloose/syntastic'
Plug 'majutsushi/tagbar' " require exuberant-ctags
Plug 'vim-airline/vim-airline'
Plug 'vim-airline/vim-airline-themes'
Plug 'terryma/vim-multiple-cursors'
Plug 'mhinz/vim-signify'
Plug 'garbas/vim-snipmate' | Plug 'honza/vim-snippets' | Plug 'tomtom/tlib_vim' | Plug 'MarcWeber/vim-addon-mw-utils'
Plug 'junegunn/vim-easy-align'
Plug 'othree/html5.vim'
Plug 'ap/vim-css-color'
Plug 'pangloss/vim-javascript'
Plug '1995eaton/vim-better-javascript-completion'
Plug 'vim-ruby/vim-ruby'
Plug 'slim-template/vim-slim'
Plug 'noprompt/vim-yardoc'
Plug 'scrooloose/nerdcommenter'
Plug 'morhetz/gruvbox'
Plug 'Misaflo/vim-markdown-preview', { 'branch': 'markdown_preview_pandoc_css' } " require pandoc
Plug 'dpelle/vim-Grammalecte'

call plug#end()

"====================
" General
"====================

let mapleader=","
set background=dark
let g:gruvbox_italic=1
colorscheme gruvbox

set number
set encoding=utf-8
set fileencoding=utf-8

set showmatch         " When a bracket is inserted, briefly jump to the matching one
set laststatus=2      " Always display the status line
set showcmd           " Show (partial) command in the last line of the screen
set wildmenu          " Command-line completion enhanced
set scrolloff=2       " Minimal number of screen lines to keep above and below the cursor
set cursorline        " Highlight the screen line of the cursor
set mouse=n           " Enable Mouse en normal mode.

set hlsearch          " When there is a previous search pattern, highlight all its matches
set ignorecase        " Ignoring case in a pattern
set incsearch         " While typing a search command, show where the pattern, as it was typed so far, matches

set smartindent       " Do smart autoindenting when starting a new line
set tabstop=2         " Number of spaces that a <Tab> in the file counts for
set shiftwidth=2      " Alignment with '<' and '>'
set expandtab         " Use spaces instead of tab

" Highlighted off
nmap <silent> <leader><space> :noh<CR>

hi SpellBad cterm=underline ctermfg=red
hi SpellCap cterm=underline ctermfg=33

if &diff
  set cursorline!
endif

" Show special characters
" Insert a non-breaking space: <C-k> <space> <space>
set list
set listchars=tab:>\ ,trail:\ ,nbsp:+
highlight NoSpacesEOL ctermbg=red ctermfg=white guibg=#592929
match NoSpacesEOL / \+$/

" :W sudo saves the file
command W w !sudo tee % > /dev/null


" ==== neovim ====
if has("nvim")
  " Map <Esc> to exit terminal-mode
  tnoremap <Esc> <C-\><C-n>

  " Live substitution
  se inccommand=nosplit

  " 24-bit color
  if has("termguicolors")
    set termguicolors
  endif
endif


"====================
" Buffer
"====================

" https://joshldavis.com/2014/04/05/vim-tab-madness-buffers-vs-tabs/
" This allows buffers to be hidden if you've modified a buffer
set hidden
" Move to the next buffer
nmap <leader>n :bnext!<CR>
" Move to the previous buffer
nmap <leader>p :bprevious!<CR>
" Close the current buffer and move to the previous one
" This replicates the idea of closing a tab
nmap <leader>q :bp <BAR> bd #<CR>

"====================
" File explorer (netrw)
"====================

" https://shapeshed.com/vim-netrw/
let g:netrw_banner = 0
let g:netrw_liststyle = 3
let g:netrw_browse_split = 4
let g:netrw_winsize = 16
let g:netrw_list_hide= '\(^\|\s\s\)\zs\.\S\+' " https://vi.stackexchange.com/questions/18650/how-to-make-netrw-start-with-dotfiles-hidden/

" https://www.reddit.com/r/vim/comments/6jcyfj/toggle_lexplore_properly/
let g:NetrwIsOpen=0
function! ToggleNetrw()
  if g:NetrwIsOpen
    let i = bufnr("$")
    while (i >= 1)
      if (getbufvar(i, "&filetype") == "netrw")
        silent exe "bwipeout " . i
      endif
      let i-=1
    endwhile
    let g:NetrwIsOpen=0
  else
    let g:NetrwIsOpen=1
    silent Lexplore
  endif
endfunction

nmap <silent> <F9> :call ToggleNetrw()<CR>

"====================
" Syntax
"====================

autocmd BufEnter todo set filetype=todo

"====================
" PHP
"====================

let php_sql_query=1       " SQL syntax highlighting inside Strings
let php_htmlInStrings=1   " Enable HTML syntax highlighting inside strings

"====================
" Ruby
"====================

" see :help ft-ruby-omni

"autocmd FileType ruby,eruby let g:rubycomplete_rails = 1
"autocmd FileType ruby,eruby let g:rubycomplete_buffer_loading = 1 " This may cause some code execution
"autocmd FileType ruby,eruby let g:rubycomplete_classes_in_global = 1
"autocmd FileType ruby,eruby let g:rubycomplete_include_object = 1
"autocmd FileType ruby,eruby let g:rubycomplete_include_objectspace = 1
let ruby_spellcheck_strings = 1

"====================
" Completion
"====================

set completeopt=menuone,preview

" If you prefer the Omni-Completion tip window to close when a selection is
" made, these lines close it on movement in insert mode or when leaving
" insert mode
autocmd CursorMovedI  * if pumvisible() == 0|pclose|endif
autocmd InsertLeave   * if pumvisible() == 0|pclose|endif

" For completion of words (ctrl + x ctrl + k)
set dictionary+=/usr/share/dict/words

"====================
" Spellchecking
"====================

" Vim spell checker (z=)
hi SpellBad guisp=red gui=undercurl guifg=NONE guibg=NONE ctermfg=white ctermbg=red term=underline cterm=none
if has("spell")
  map <leader>lf :set spell spelllang=fr<cr>
  map <leader>le :set spell spelllang=en<cr>
  map <leader>ln :set nospell<cr>
endif

set spellsuggest=5

"====================
" Automatic headers
"====================

autocmd bufnewfile *.sh   so ~/.config/nvim/header/sh
autocmd bufnewfile *.php  so ~/.config/nvim/header/php
autocmd bufnewfile *.rb   so ~/.config/nvim/header/ruby

"====================
" Plugins configuration
"====================

" vim-yardoc
hi link yardGenericTag  rubyInstanceVariable
hi link yardType        Type
hi link yardLiteral     Type

" vim-airline
let g:airline#extensions#whitespace#enabled = 0
let g:airline_theme='base16_grayscale'
let g:airline#extensions#tabline#enabled = 1

" vim-signify
let g:signify_vcs_list = [ 'git' ]

" tagbar
nmap <F8> :TagbarToggle<CR>

" syntastic
let g:syntastic_always_populate_loc_list = 1
let g:syntastic_auto_loc_list = 1
let g:syntastic_check_on_open = 1
let g:syntastic_check_on_wq = 0
let g:syntastic_loc_list_height = 5
" Ignore warings for eruby
autocmd FileType eruby let g:syntastic_quiet_messages = {"level": "warnings"}

" vim-javascript
let g:javascript_plugin_jsdoc = 1 " Enables syntax highlighting for JSDocs

" easy-align
" Start interactive EasyAlign in visual mode (e.g. vip<Enter>)
vmap <Enter> <Plug>(EasyAlign)

" nerdcommenter
nnoremap <leader>c :call NERDComment(0,"toggle")<CR>
vnoremap <leader>c :call NERDComment(0,"toggle")<CR>

" vim-markdown-preview
let vim_markdown_preview_hotkey='<C-m>'
let vim_markdown_preview_pandoc=1
let vim_markdown_preview_pandoc_css='$HOME/.dotfiles/vim/github-pandoc.css'
let vim_markdown_preview_use_xdg_open=1

" vim-Grammalecte
let g:grammalecte_cli_py='~/.dotfiles/vim/grammalecte/grammalecte-cli.py'
hi GrammalecteGrammarError  guisp=lightBlue gui=undercurl guifg=NONE guibg=NONE ctermfg=white ctermbg=blue term=underline cterm=none
hi GrammalecteSpellingError guisp=red       gui=undercurl guifg=NONE guibg=NONE ctermfg=white ctermbg=red  term=underline cterm=none
